name: Build_and_Test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: actions/setup-node@v4
        with: 
          node-version: 12.13.0 
          
      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

  #    - name: Report
   #     uses: dorny/test-reporter@v1
    #    if: always()
     #   with:
      #    name: Maven Tests
       #   path: target/surefire-reports/*.xml
        #  reporter: java-junit
         # fail-on-error: true
    #  - name: Maven Verify
    #    run: mvn clean install verify -B
