name: Build_and_Test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'
      - 'rc'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: actions/setup-node@v4
        with:
          node-version: 12.13.0
      - name: Build
        run: mvn -DskipTests package

  module_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: actions/setup-node@v4
        with:
          node-version: 12.13.0
      - name: Module tests
        run: mvn -B test -Dtest=**/module_tests/**

  integration_tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: actions/setup-node@v4
        with:
          node-version: 12.13.0
      - name: Fill tables
        run: PGPASSWORD=root psql -h localhost -U postgres -d postgres -f fill-tables.sql
      - name: Run Integration Tests
        run: mvn -B test -Dtest=**/integration/**
#
#  start_application:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#      - name: set up JDK 17
#        uses: actions/setup-java@v1
#        with:
#          java-version: 17
#      - name: Start Application
#        run: |
#          mvn spring-boot:run
#          sleep 1m

  e2e_tests:
#    needs: start_application
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@v2
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Checkout repository
        uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Fill tables
        run: PGPASSWORD=root psql -h localhost -U postgres -d postgres -f fill-tables.sql
      - name: Run E2E tests
        run: mvn -B package test -Dtest=**/end2end/**


